# Change these first
owner: vtkmco # Your GitHub organization or username, where this repository lives
repo: git_uptime # The name of this repository

sites:
  - name: Authentik
    url: https://auth.vtk2m.xyz
  - name: VaultWarden
    url: https://vw.vtk2m.xyz
  - name: NextCloud
    url: https://nextcloud.vtk2m.xyz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /git_uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "@Jarvis Services Uptime"
  introMessage: Hello! Uptime Status
  navbar:
    - title: Status
      href: /
    - title: JArvis_Uptime
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
